schemaVersion = "1.0"
id = "lcod://resolver/internal/lock-path@1"
name = "lock-path"
namespace = "resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Compute the destination path for the resolver lockfile."

[tool]
name = "lock_path"
description = "Select the lock path from project/output inputs."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://axiom/path/join@1",
  "lcod://impl/set@1"
]

[docs]
readme = "README.md"
