schemaVersion = "1.0"
id = "lcod://resolver/internal/resolve-dependencies@1"
name = "resolve-dependencies"
namespace = "resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Resolve the dependency graph for the resolver using normalized configuration and cache info."

[tool]
name = "resolve_dependencies"
description = "Traverse dependency tree, applying replacements, allowlists and cache lookups."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/path/join@1",
  "lcod://axiom/fs/read-file@1",
  "lcod://axiom/toml/parse@1",
  "lcod://contract/core/hash/sha256@1",
  "lcod://contract/core/git/clone@1",
  "lcod://axiom/http/download@1"
]

[docs]
readme = "README.md"
