schemaVersion = "1.0"
id = "lcod://resolver/internal/summarize-result@1"
name = "summarize-result"
namespace = "resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Extract dependency graph, integrity and warnings from resolver output."

[tool]
name = "summarize_result"
description = "Summarise resolverResult into dependency graph data."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://tooling/script@1"
]

[docs]
readme = "README.md"
