schemaVersion = "1.0"
id = "lcod://resolver/internal/build-lock@1"
name = "build-lock"
namespace = "resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Build the resolver lock document and TOML text from the dependency graph."

[tool]
name = "build_lock"
description = "Assemble the lock payload from resolver state."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://tooling/script@1",
  "lcod://axiom/toml/stringify@1",
  "lcod://impl/set@1"
]

[docs]
readme = "README.md"
