schemaVersion = "1.0"
id = "lcod://tooling/resolver/internal/load-config@0.1.0"
name = "load-config"
namespace = "tooling/resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Load and normalise resolver configuration from JSON, falling back to empty sources."

[tool]
name = "load_config"
description = "Resolve the configuration JSON used by the resolver pipeline."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://axiom/path/join@1",
  "lcod://tooling/fs/read_optional@0.1.0",
  "lcod://tooling/json/decode_object@0.1.0",
  "lcod://tooling/value/default_object@0.1.0",
  "lcod://tooling/value/default_array@0.1.0",
  "lcod://tooling/value/is_string_nonempty@0.1.0",
  "lcod://tooling/array/append@0.1.0",
  "lcod://core/object/merge@0.1.0",
  "lcod://impl/set@1"
]

[docs]
readme = "README.md"
