schemaVersion = "2.0"
id = "lcod://tooling/resolver/internal/lock-path@0.1.0"
version = "0.1.0"
kind = "function"
summary = "Compute the destination path for the resolver lockfile."

[deps]
requires = [
  "lcod://flow/if@1",
  "lcod://axiom/path/join@1",
  "lcod://impl/set@1"
]

[inputs.projectPath]
summary = "Project root directory."
required = true
schema = """
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "string",
  "minLength": 1,
  "description": "Project root path."
}"""

[inputs.outputPath]
summary = "Explicit destination path for the lockfile."
required = false
schema = """
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "string",
  "minLength": 1,
  "description": "Explicit destination path for the lockfile."
}"""

[outputs.lockPath]
summary = "Resolved lockfile destination."
schema = """
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "string",
  "description": "Lockfile destination."
}"""

[tool]
name = "lock_path"
description = "Normalise project/output inputs into a single lockfile path."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"
