schemaVersion = "1.0"
id = "lcod://resolver/internal/prepare-config@1"
name = "prepare-config"
namespace = "resolver/internal"
version = "0.1.0"
kind = "function"
summary = "Normalize resolver configuration (sources, replacements, allowlist) and propagate warnings."

[tool]
name = "prepare_config"
description = "Prepare normalized configuration state for dependency resolution."
inputSchema = "schema/input.json"
outputSchema = "schema/output.json"

[deps]
requires = [
  "lcod://tooling/script@1"
]

[docs]
readme = "README.md"
