compose:
  - call: lcod://tooling/resolver/cache-dir@1
    in:
      projectPath: $.projectPath
    out:
      cacheInfo: $

  - call: lcod://impl/set@1
    in:
      candidateRoot: $.projectPath
    out:
      candidateRoot: candidateRoot

  - call: lcod://tooling/value/is_string_nonempty@0.1.0
    in:
      value: $.cacheInfo.path
    out:
      hasCachePath: ok

  - call: lcod://flow/if@1
    in:
      cond: $.hasCachePath
    slots:
      then:
        - call: lcod://impl/set@1
          in:
            candidateRoot: $.cacheInfo.path
          out:
            candidateRoot: candidateRoot
    out:
      candidateRoot: candidateRoot

  - call: lcod://axiom/path/join@1
    in:
      base: $.candidateRoot
      segment: "."
    out:
      normalizedJoin: $

  - call: lcod://tooling/value/is_string_nonempty@0.1.0
    in:
      value: $.normalizedJoin.path
    out:
      hasNormalized: ok

  - call: lcod://flow/if@1
    in:
      cond: $.hasNormalized
    slots:
      then:
        - call: lcod://impl/set@1
          in:
            cacheRoot: $.normalizedJoin.path
          out:
            cacheRoot: cacheRoot
      else:
        - call: lcod://impl/set@1
          in:
            cacheRoot: $.candidateRoot
          out:
            cacheRoot: cacheRoot
    out:
      cacheRoot: cacheRoot
